const fs = require('fs');

let code = fs.readFileSync('src/components/Layout.tsx', 'utf-8');

// Replace navItems
code = code.replace(
  "const navItems = [",
  "const navItems = [\n  { id: 'students', label: 'Öğrenci Kayıtları', shortLabel: 'Öğrenciler', icon: Users, colorClass: 'text-blue-400', hoverColorClass: 'group-hover:text-blue-400', activeClass: 'bg-blue-500/10 border-blue-400 border-l-2 pl-3 text-white font-semibold' },\n  { id: 'exams', label: 'Deneme Sınavları', shortLabel: 'Sınavlar', icon: Calendar, colorClass: 'text-indigo-400', hoverColorClass: 'group-hover:text-indigo-400', activeClass: 'bg-indigo-500/10 border-indigo-400 border-l-2 pl-3 text-white font-semibold' },\n  { id: 'results', label: 'Sınav Sonuçları', shortLabel: 'Sonuçlar', icon: BarChart2, colorClass: 'text-emerald-400', hoverColorClass: 'group-hover:text-emerald-400', activeClass: 'bg-emerald-500/10 border-emerald-400 border-l-2 pl-3 text-white font-semibold' },\n  { id: 'league', label: 'Akademi Arena', shortLabel: 'Arena', icon: Trophy, colorClass: 'text-amber-400', hoverColorClass: 'group-hover:text-amber-400', activeClass: 'bg-amber-500/10 border-amber-400 border-l-2 pl-3 text-white font-semibold' },\n  { id: 'halls', label: 'Sınav Salonları', shortLabel: 'Salonlar', icon: LayoutTemplate, colorClass: 'text-pink-400', hoverColorClass: 'group-hover:text-pink-400', activeClass: 'bg-pink-500/10 border-pink-400 border-l-2 pl-3 text-white font-semibold' },\n  { id: 'budget', label: 'Bütçe Takibi', shortLabel: 'Bütçe', icon: DollarSign, colorClass: 'text-cyan-400', hoverColorClass: 'group-hover:text-cyan-400', activeClass: 'bg-cyan-500/10 border-cyan-400 border-l-2 pl-3 text-white font-semibold' },\n];\n/*"
);
code = code.replace("];", "];\n*/"); // close the comment for the old items
code = code.replace("];\n*/\n/*", "];\n/*");

// Add Settings to lucide-react imports
code = code.replace("Menu, X } from 'lucide-react'", "Menu, X, Settings } from 'lucide-react'");

// Replace Sidebar with hidden md:flex
code = code.replace(
  'fixed inset-y-0 left-0 z-50 w-[280px] bg-brand-sidebar-bg text-white flex flex-col p-6 md:p-8 justify-between border-r border-white/5 overflow-y-auto transition-transform duration-300 ease-in-out md:relative md:translate-x-0 shrink-0",\n        isMobileMenuOpen ? "translate-x-0" : "-translate-x-full"',
  'hidden md:flex fixed inset-y-0 left-0 z-50 w-[280px] bg-brand-sidebar-bg text-white flex-col p-8 justify-between border-r border-white/5 overflow-y-auto relative translate-x-0 shrink-0"'
);

// Replace the main area
code = code.replace(
  '      {/* Main Content */}\n      <main className={cn("flex-1 flex flex-col overflow-auto bg-brand-bg transition-all duration-300 w-full", isDarkMode ? "dark-mode-main" : "")}>\n        \n        {/* Mobile Header */}\n        <header className="md:hidden flex items-center justify-between p-4 bg-brand-sidebar-bg text-white border-b border-white/5 shrink-0">\n          <div className="flex items-center gap-3">\n            <button onClick={() => setIsMobileMenuOpen(true)} className="text-white/80 hover:text-white p-1">\n              <Menu className="w-6 h-6" />\n            </button>\n            <h1 className="font-serif text-lg italic font-semibold tracking-tight">AkademiPanel</h1>\n          </div>\n        </header>',
  '      {/* Main Content */}\n      <main className={cn("flex-1 flex flex-col overflow-auto bg-brand-bg transition-all duration-300 w-full pb-[70px] md:pb-0", isDarkMode ? "dark-mode-main" : "")}>\n        \n        {/* Mobile Header */}\n        <header className="md:hidden flex items-center justify-between p-4 bg-brand-sidebar-bg text-white border-b border-white/5 shrink-0 sticky top-0 z-30">\n          <div className="flex items-center gap-3">\n            <h1 className="font-serif text-xl italic font-semibold tracking-tight">AkademiPanel</h1>\n          </div>\n          <button onClick={() => setIsMobileMenuOpen(true)} className="text-white/80 hover:text-white p-1">\n            <Settings className="w-6 h-6" />\n          </button>\n        </header>'
);

// Replace mobile menu overlay and logic
code = code.replace(
  '      {/* Mobile Menu Overlay */}\n      {isMobileMenuOpen && (\n        <div \n          className="fixed inset-0 bg-black/50 z-40 md:hidden"\n          onClick={closeMobileMenu}\n        />\n      )}',
  `      {/* Mobile Settings Overlay */}\n      {isMobileMenuOpen && (\n        <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center bg-black/60 backdrop-blur-sm md:hidden" onClick={closeMobileMenu}>\n          <div \n            className="w-full bg-brand-sidebar-bg rounded-t-[32px] sm:rounded-2xl p-6 pb-safe flex flex-col gap-3 animate-slide-up"\n            onClick={(e) => e.stopPropagation()}\n          >\n            <div className="flex items-center justify-between mb-2">\n              <h3 className="text-white font-serif text-2xl font-bold">Seçenekler</h3>\n              <button onClick={closeMobileMenu} className="text-white/60 hover:text-white p-2 bg-white/5 rounded-full">\n                <X className="w-5 h-5" />\n              </button>\n            </div>\n            \n            <input type="file" accept=".json" className="hidden" id="restore-input-mobile" onChange={handleRestore} />\n            <button onClick={handleSave} className="flex items-center justify-center w-full bg-white/5 hover:bg-white/10 text-white text-sm font-semibold py-3.5 px-4 rounded-xl border border-white/10 transition-all gap-2">\n              <Save className="w-4 h-4" /> Değişiklikleri Kaydet\n            </button>\n            <button onClick={() => document.getElementById('restore-input-mobile')?.click()} className="flex items-center justify-center w-full bg-white/5 hover:bg-white/10 text-white text-sm font-semibold py-3.5 px-4 rounded-xl border border-white/10 transition-all gap-2">\n              <UploadCloud className="w-4 h-4" /> Yedeği İçe Aktar\n            </button>\n            <button onClick={handleBackup} className="flex items-center justify-center w-full bg-brand-accent hover:bg-[#c4a46e] text-white text-sm font-semibold py-3.5 px-4 rounded-xl border border-brand-accent transition-all gap-2 shadow-sm">\n              <DownloadCloud className="w-4 h-4" /> Sistemi Yedekle (İndir)\n            </button>\n            \n            <div className="w-full h-px bg-white/10 my-1"></div>\n            \n            <button onClick={() => setIsDarkMode(!isDarkMode)} className="flex items-center justify-center w-full bg-white/5 hover:bg-white/10 text-white text-sm font-semibold py-3.5 px-4 rounded-xl border border-white/10 transition-all gap-2">\n              {isDarkMode ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}\n              {isDarkMode ? 'Aydınlık Temaya Geç' : 'Karanlık Temaya Geç'}\n            </button>\n          </div>\n        </div>\n      )}`
);

// Add Bottom Nav
code = code.replace(
  '    </div>\n  );\n};',
  `\n      {/* Mobile Bottom Navigation */}\n      <nav className="md:hidden fixed bottom-0 left-0 right-0 bg-brand-sidebar-bg border-t border-white/5 z-40 flex items-center justify-around px-1 py-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] shadow-[0_-8px_30px_rgba(0,0,0,0.12)]">\n        {navItems.map((item) => {\n          const isActive = activeTab === item.id;\n          return (\n            <button\n              key={item.id}\n              onClick={() => setActiveTab(item.id)}\n              className="flex flex-col items-center justify-center w-full py-1 gap-1 transition-all"\n            >\n              <div className={cn(\n                "p-1.5 rounded-full transition-colors", \n                isActive ? "bg-white/10" : "bg-transparent"\n              )}>\n                <item.icon className={cn(\n                  "w-[22px] h-[22px] transition-colors",\n                  isActive ? item.colorClass : "text-white/40"\n                )} />\n              </div>\n              <span className={cn(\n                "text-[10px] font-semibold tracking-tight truncate px-0.5",\n                isActive ? "text-white" : "text-white/40"\n              )}>\n                {item.shortLabel}\n              </span>\n            </button>\n          );\n        })}\n      </nav>\n    </div>\n  );\n};`
);

fs.writeFileSync('src/components/Layout.tsx', code);
